general {
  disable_loading_bar = true
  hide_cursor = true
}

background {
  monitor =
  color = rgba(1a1b26ff)
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +'%H:%M')"
  font_family = JetBrainsMono Nerd Font
  font_size = 64
  position = 0, 120
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:60000] echo "$(date +'%A, %d/%m/%Y')"
  font_family = Noto Sans
  font_size = 18
  position = 0, 55
  halign = center
  valign = center
}

input-field {
  monitor =
  size = 300, 50
  outline_thickness = 2
  dots_size = 0.25
  dots_spacing = 0.25
  dots_center = true
  fade_on_empty = false
  placeholder_text = <i>Senha...</i>
  fail_text = <i>Falha na autenticação</i>
  position = 0, -40
  halign = center
  valign = center
}
