export ZSH="$HOME/.local/share/oh-my-zsh"
ZSH_THEME=""
plugins=(git)

source "$ZSH/oh-my-zsh.sh"

for module in \
  environment.zsh \
  aliases.zsh \
  completion.zsh \
  functions.zsh \
  integrations.zsh \
  prompt.zsh; do
  source "$ZDOTDIR/modules/$module"
done
